name: Murni Rakit Boot Vince

on:
  workflow_dispatch:

jobs:
  porting-boot:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Bahan Dari Repo
        uses: actions/checkout@v4

      - name: Proses Tukar Ramdisk Halium
        run: |
          H="https://"
          A="raw.github"
          B="usercontent.com"
          
          # Ambil alat tempur resmi
          curl -sLo unpackbootimg "${H}${A}${B}/osm0sis/mkbootimg/master/unpackbootimg" && chmod +x unpackbootimg
          curl -sLo mkbootimg "${H}${A}${B}/osm0sis/mkbootimg/master/mkbootimg" && chmod +x mkbootimg
          
          mkdir -p ori halium ramdisk_halium ramdisk_ori out_boot
          
          # Eksekusi pembongkaran bahan yang sudah Anda upload
          ./unpackbootimg -i boot.img -o ori/
          ./unpackbootimg -i halium-boot.img -o halium/

          # Bongkar ramdisk halium dan ramdisk ori vince
          cd ramdisk_halium && gzip -d -c ../halium/ramdisk | cpio -i 2>/dev/null
          cd ../ori/ramdisk_ori && gzip -d -c ../ramdisk | cpio -i 2>/dev/null

          # Suntikkan komponen halium
          cp -rf ../../ramdisk_halium/init* ./
          cp -rf ../../ramdisk_halium/sbin* ./ 2>/dev/null || true
          cp -rf ../../ramdisk_halium/lib* ./ 2>/dev/null || true

          # Bungkus ulang ramdisk porting
          find . | cpio -o -H newc 2>/dev/null | gzip > ../ramdisk_new
          cd ..

          # Rakit final menjadi file tunggal halium-boot-vince.img
          ./mkbootimg --kernel kernel --ramdisk ramdisk_new --dtb dtb --cmdline "$(cat cmdline)" --base $(cat base) --pagesize $(cat pagesize) --kernel_offset $(cat kernel_offset) --ramdisk_offset $(cat ramdisk_offset) --tags_offset $(cat tags_offset) -o ../out_boot/halium-boot-vince.img

      - name: Unggah Hasil Boot .img Ukuran Kecil
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-Boot-Vince-Murni
          path: out_boot/halium-boot-vince.img
