name: Rilis Kilat Depan
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Unduh Instan Artifact dari Run Sukses
        uses: actions/download-artifact@v4
        with:
          name: Droidian-Hybrid-ZIP-Vince
          run-id: 37425386446
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cari dan Pindahkan File ke Folder Rilis
        run: |
          mkdir -p output_release
          find . -maxdepth 2 -name "*.zip" -exec mv {} output_release/ \;
          
      - name: Lempar Langsung ke Halaman Depan Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0-stable"
          name: "Droidian Vince Hybrid Installer Stable"
          body: "File installer hibrida siap pakai untuk Xiaomi Redmi 5 Plus (vince). Unduh langsung di halaman depan."
          files: output_release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
